[project]
name = "quadratic-sign"
authors = ["QuadSign Team"]
description = "Decentralized quadratic signaling and reputation system"
telemetry = false
requirements = []
[contracts.quadratic-signal]
path = "contracts/quadratic-signal.clar"
depends_on = []

[contracts.reputation-manager]
path = "contracts/reputation-manager.clar"
depends_on = []

[contracts.signal-allocation]
path = "contracts/signal-allocation.clar"
depends_on = []

[contracts.signal-registry]
path = "contracts/signal-registry.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
